receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "localhost:8889"
    namespace: otel
    const_labels:
      source_app: promitor
    send_timestamps: true

processors:
  batch:

extensions:

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
