receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: otel
    const_labels:
      source_app: promitor
    send_timestamps: true

processors:
  batch:

extensions:

service:
  extensions: []
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
