server:
  httpPort: 88
metricSinks:
  openTelemetryCollector:
    collectorUri: http://#{Container.OpenTelemetryCollector.Name}#:4317
  prometheusScrapingEndpoint:
    metricUnavailableValue: NaN
    enableMetricTimestamps: true # true by default
    baseUriPath: /metrics
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace
azureMonitor:
  integration:
    metricsBatching:
      enabled: true 
      maxBatchSize: 2 
  logging:
    isEnabled: false
resourceDiscovery:
  host: #{Container.ResourceDiscovery.Name}#
  port: 99